name: tech_in_church
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  another_flushbar: ^1.10.5
  auto_route: ^1.0.2
  better_player: ^0.0.62
  bubble: ^1.2.1
  cached_network_image: ^3.0.0
  carousel_slider: ^2.3.1
  cupertino_icons: ^1.0.2
  dartz: ^0.9.0-dev.6
  data_connection_checker: ^0.3.4
  date_format: ^2.0.2
  dio: ^4.0.0-beta7
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.2
#  flushbar: ^1.10.4
  flutter_bloc: ^7.0.0
#  flutter_login_facebook: ^1.2.0
  flutter_facebook_login: ^3.0.0
  flutter_holo_date_picker: ^0.3.2
  flutter_hooks: ^0.16.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_ringtone_player: ^3.0.0
  flutter_screenutil: ^4.0.3+3
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_swiper: ^1.1.6
  flutter_widget_from_html: ^0.6.0
  font_awesome_flutter: ^9.0.0
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0
  google_sign_in: ^5.2.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image_picker: ^0.7.2+1
  implicitly_animated_reorderable_list: ^0.3.2
  infinite_scroll_pagination: ^3.0.1
  injectable: ^1.2.0
  json_annotation: ^4.0.0
  just_audio: ^0.7.3
  meta: ^1.3.0
#  overlay_support: ^1.2.1
  pagination: ^0.1.0
  path_provider: ^2.0.1
  readmore: ^2.0.0
  reorderables: ^0.3.2
  rxdart: ^0.26.0
  scroll_to_index: ^2.0.0
  seekbar: ^0.0.2
  sign_in_with_apple: ^3.0.0
  stripe_payment: ^1.1.4
  styled_widget: ^0.2.2
  table_calendar: ^2.3.3
  time: ^2.0.0
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.9
  chewie: ^1.0.0
  badges: ^2.0.1
  flutter_credit_card: ^3.0.1

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner: ^1.11.5
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.0.3
  freezed: ^0.14.1+1
  hive_generator: ^1.0.0
  injectable_generator: ^1.2.0
  json_serializable: ^4.0.2
  lint: ^1.5.3
  pretty_dio_logger: ^1.1.1
  awesome_notifications: ^0.0.5+8
  liquid_pull_to_refresh: ^3.0.0
  timezone: ^0.7.0
  flutter_native_timezone: ^2.0.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter_native_splash:
  image: assets/images/splash.png
  fullscreen: true
  android12: true
  color: "#33AFFF"
  android_gravity: fill

